global:
  scrape_interval: 5s

scrape_configs:
  # - job_name: prometheus
  #   static_configs:
  #     - targets: ['localhost:9090']

  - job_name: repo-watch
    static_configs:
      - targets: ['host.docker.internal:3000']
    authorization:
      type: Bearer
      credentials: metrics-endpoint-guard-api-key
